### ISSUE TITLE
please could you provide .apk package

### ISSUE THREAD

**Issue by JanuszChmiel** [io12/WineBox86.apk#4]
Dear IO12, Do you think, that it would be possible to create .apk package? Or project is in so unstable, that it is not possible to release some debug .apk package for testers?
Project look very promise. It would be very interesting to have some emulator, which could run some Windows APPs even on non rooted ARM devices with Android OS.
Thank you for yours answer.

**Comment by io12** [comment]
Thanks for the interest! But yeah any .apk at this point would not work, sorry.
